---
# This is a sample configmap that helps define a Ceph configuration as required
# by the CSI plugins.

# Sample ceph.conf available at
# https://github.com/ceph/ceph/blob/master/src/sample.ceph.conf Detailed
# documentation is available at
# https://docs.ceph.com/en/latest/rados/configuration/ceph-conf/
apiVersion: v1
kind: ConfigMap
data:
  ceph.conf: |
    [global]
    auth_cluster_required = cephx
    auth_service_required = cephx
    auth_client_required = cephx
    mon host = 10.2.36.9:6789,10.2.36.10:6789,10.2.36.11:6789

  # keyring is a required key and its value should be empty
  keyring: |
    [client.admin]
        key = AQAhettdAAAAABAAEER/quKJylhED6vQx7c8Vw==
        caps mds = "allow *"
        caps mgr = "allow *"
        caps mon = "allow *"
        caps osd = "allow *"
metadata:
  name: ceph-config
